stats = [
    ("生命值 (HP)", "生命值", "HP"),
    ("魔法值 (MP)", "魔法值", "MP"),
    ("力量 (Strength)", "力量", "Strength"),
    ("智力 (Intelligence)", "智力", "Intelligence"),
    ("体力 (Physical Strength)", "体力", "Physical Strength"),
    ("精神 (Spirit)", "精神", "Spirit"),
    ("物理攻击力 (Physical Attack Power)", "物理攻击力", "Physical Attack Power"),
    ("魔法攻击力 (Magical Attack Power)", "魔法攻击力", "Magical Attack Power"),
    ("物理防御力 (Physical Defense)", "物理防御力", "Physical Defense"),
    ("魔法防御力 (Magical Defense)", "魔法防御力", "Magical Defense"),
    ("物理暴击 (Physical Critical Hit)", "物理暴击", "Physical Critical Hit"),
    ("魔法暴击 (Magical Critical Hit)", "魔法暴击", "Magical Critical Hit"),
    ("攻击速度 (Attack Speed)", "攻击速度", "Attack Speed"),
    ("施法速度 (Casting Speed)", "施法速度", "Casting Speed"),
    ("移动速度 (Movement Speed)", "移动速度", "Movement Speed"),
    ("火属性强化 (Fire Enhance)", "火属性强化", "Fire Enhance"),
    ("冰属性强化 (Ice Enhance)", "冰属性强化", "Ice Enhance"),
    ("光属性强化 (Light Enhance)", "光属性强化", "Light Enhance"),
    ("暗属性强化 (Dark Enhance)", "暗属性强化", "Dark Enhance"),
    ("火属性抗性 (Fire Resistance)", "火属性抗性", "Fire Resistance"),
    ("冰属性抗性 (Ice Resistance)", "冰属性抗性", "Ice Resistance"),
    ("光属性抗性 (Light Resistance)", "光属性抗性", "Light Resistance"),
    ("暗属性抗性 (Dark Resistance)", "暗属性抗性", "Dark Resistance")
]